name: Bug Report
description: File a bug report
title: ""
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of MusicDJ are you running?
      placeholder: Eg. v1.2.2-beta
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: OS/Browser version
      placeholder: Eg. Chrome 92 on Windows 10 19043
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device information (phone model or PC specs)
      placeholder: Eg. Pixel 4
    validations:
      required: false
  - type: textarea
    id: media
    attributes:
      label: Screenshots / Videos
      description: You can upload screenshots or videos showing the issue.
