name: Feature request
description: Propose a feature
title: "[Feature]: "
labels: [enhancement]

body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem you're having 
      description: Is your feature request related to a problem? Please describe.
      placeholder: E.g. I'm always frustrated when [...]
    validations:
      required: true
- type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like 
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
- type: textarea
    id: media
    attributes:
      label: Screenshots
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
